#workflow
name: MERN App CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-backend:latest ./server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-backend:latest
      
      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-frontend:latest ./client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-frontend:latest
      
      - name: Deploy to DigitalOcean Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest images from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-frontend:latest
            
            # Stop and remove old containers to avoid conflicts
            docker stop mern-backend mern-frontend || true
            docker rm mern-backend mern-frontend || true
            
            # Run the new containers
            docker run -d --name mern-backend -p 5000:5000 --restart always -e MONGO_URI="${{ secrets.MONGO_URI }}" ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-backend:latest
            docker run -d --name mern-frontend -p 3000:3000 --restart always ${{ secrets.DOCKERHUB_USERNAME }}/mern-cicd-frontend:latest